[default.extend-words]
alikes = "alikes"
anc = "anc"
ba = "ba"
beng = "beng"
fo = "fo"
ist = "ist"
iy = "iy"
jod = "jod"
mis = "mis"
nd = "nd"
pn = "pn"
som = "som"
writeable = "writeable"
xdescribe = "xdescribe"
