#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Op {
    LoadConst = 0,
    LoadUndefined = 1,
    Return = 2,
    ReturnUndefined = 3,
    Add = 4,
    Sub = 5,
    Mul = 6,
    Div = 7,
    Mod = 8,
    Pow = 9,
    Eq = 10,
    NotEq = 11,
    StrictEq = 12,
    StrictNotEq = 13,
    Lt = 14,
    Gt = 15,
    LtEq = 16,
    GtEq = 17,
    BitAnd = 18,
    BitOr = 19,
    BitXor = 20,
    Shl = 21,
    Shr = 22,
    UShr = 23,
    Neg = 24,
    Plus = 25,
    Not = 26,
    BitNot = 27,
    Pop = 28,
    LoadTrue = 29,
    LoadFalse = 30,
    LoadNull = 31,
    Jump = 32,
    JumpIfFalse = 33,
    JumpIfTrue = 34,
    JumpIfTruthyKeep = 35,
    JumpIfFalsyKeep = 36,
    JumpIfNotNullishKeep = 37,
    LoadName = 38,
    StoreName = 39,
}

impl Op {
    pub(crate) fn from_u8(b: u8) -> Option<Op> {
        match b {
            0 => Some(Op::LoadConst),
            1 => Some(Op::LoadUndefined),
            2 => Some(Op::Return),
            3 => Some(Op::ReturnUndefined),
            4 => Some(Op::Add),
            5 => Some(Op::Sub),
            6 => Some(Op::Mul),
            7 => Some(Op::Div),
            8 => Some(Op::Mod),
            9 => Some(Op::Pow),
            10 => Some(Op::Eq),
            11 => Some(Op::NotEq),
            12 => Some(Op::StrictEq),
            13 => Some(Op::StrictNotEq),
            14 => Some(Op::Lt),
            15 => Some(Op::Gt),
            16 => Some(Op::LtEq),
            17 => Some(Op::GtEq),
            18 => Some(Op::BitAnd),
            19 => Some(Op::BitOr),
            20 => Some(Op::BitXor),
            21 => Some(Op::Shl),
            22 => Some(Op::Shr),
            23 => Some(Op::UShr),
            24 => Some(Op::Neg),
            25 => Some(Op::Plus),
            26 => Some(Op::Not),
            27 => Some(Op::BitNot),
            28 => Some(Op::Pop),
            29 => Some(Op::LoadTrue),
            30 => Some(Op::LoadFalse),
            31 => Some(Op::LoadNull),
            32 => Some(Op::Jump),
            33 => Some(Op::JumpIfFalse),
            34 => Some(Op::JumpIfTrue),
            35 => Some(Op::JumpIfTruthyKeep),
            36 => Some(Op::JumpIfFalsyKeep),
            37 => Some(Op::JumpIfNotNullishKeep),
            38 => Some(Op::LoadName),
            39 => Some(Op::StoreName),
            _ => None,
        }
    }
}
